AWSTemplateFormatVersion: "2010-09-09"
Resources:
  CrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: WozCrossAccountRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - Fn::Sub: arn:aws:iam::216989130230:root
            Action: sts:AssumeRole
      Policies:
        - PolicyName: WoZS3ReadOnlyAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:DescribeJob
                  - s3:GetBucketPolicy
                  - s3:GetBucketPolicyStatus
                  - s3:GetBucketVersioning
                  - s3:DescribeMultiRegionAccessPointOperation
                  - s3:GetAccessPointPolicy
                  - s3:GetBucketCORS
                  - s3:GetBucketMetadataTableConfiguration
                  - s3:GetEncryptionConfiguration
                  - s3:GetMultiRegionAccessPointPolicy
                  - s3:GetMultiRegionAccessPointPolicyStatus
                  - s3:ListBucket
                  - s3:ListAllMyBuckets
                Resource: "*"
        - PolicyName: WozEC2ReadOnlyAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:Describe*"
                  - "ec2:GetSecurityGroupsForVpc"
                  - "elasticloadbalancing:Describe*"
                  - "cloudwatch:ListMetrics"
                  - "cloudwatch:GetMetricStatistics"
                  - "cloudwatch:Describe*"
                  - "autoscaling:Describe*"
                Resource: "*"
        - PolicyName: WozRDSReadOnlyAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - rds:Describe*
                  - rds:ListTagsForResource
                  - ec2:DescribeAccountAttributes
                  - ec2:DescribeAvailabilityZones
                  - ec2:DescribeInternetGateways
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeSubnets
                  - ec2:DescribeVpcAttribute
                  - ec2:DescribeVpcs
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:ListMetrics
                  - cloudwatch:GetMetricData
                  - logs:DescribeLogStreams
                  - logs:GetLogEvents
                  - devops-guru:GetResourceCollection
                Resource: "*"
